### ISSUE TITLE
Choice of Front-End Framework (i.e. Bootstrap)

### ISSUE THREAD

**Issue by Stephn-R** [gigster-eng/node-starter#10]
Bootstrap only or anything else?

**Comment by arieljake** [comment]
I'm not convinced a choice of front end needs to be packaged into this project

**Comment by Stephn-R** [comment]
Why is that the case? I see the goal of this project is to be able to pick it up and start developing front-end/nodejs services without any confusion.

**Comment by arieljake** [comment]
As I understand it, we don't always have the luxury of choosing the stack but rather need to be prepared to respond to client requests. If they want node with angular and mongo or node with mobile and MySQL or node with bootstrap and dynamodb it doesn't matter...this is a node repo for providing the node backend to the front end requested by the client. There should then be similar repos for every kind of front end.

**Comment by Stephn-R** [comment]
Ok so perhaps we should be building this project as a pure NodeJS template starter. No frontend and just purely for building Server side tools/web based services

**Comment by arieljake** [comment]
Right. That's what makes most sense to me. It also allows us to split projects where a backend guy can use this project and a front end guy uses the starter he needs. And there's no unused code in either's repo.

**Comment by Stephn-R** [comment]
Great so we will need to make sure this repo exposes one single index.html page at least and then all of our front-end repos (i.e. AngularJS-starter) can be plugged in through that index.html

**Comment by arieljake** [comment]
Not sure...there may be a more general way to handle this. Need to think about it.

**Comment by Stephn-R** [comment]
Agreed

**Comment by Stephn-R** [comment]
@arieljake Shall we leave this open ended like we are with DB systems? 

i.e.

    - client/
        - angular-app/
        - react-app/
        - ...
        - README.md
        - config.js

And the config manages which of the systems is used. And the README describes how the system works from this level.
