### ISSUE TITLE
Managing new additions to the app via a yeoman generator

### ISSUE THREAD

**Issue by Stephn-R** [gigster-eng/node-starter#12]
http://yeoman.io/authoring/

Lets build our own one!

**Comment by arieljake** [comment]
I throw it out there that a good use of design patterns and documentation should allow us to avoid using yeoman

**Comment by Stephn-R** [comment]
Ok so we are assuming that all Gigsters would follow good use of design patterns?

**Comment by arieljake** [comment]
I think if the customization of this starter kit is built on design patterns then yes future gigsters will be inclined to continue using the existing patterns

**Comment by Stephn-R** [comment]
Ok so lets make it happen then :smile:
