### ISSUE TITLE
Using passport for auth

### ISSUE THREAD

**Issue by Stephn-R** [gigster-eng/node-starter#13]
https://www.npmjs.com/package/passport

**Comment by arieljake** [comment]
The only issue I have with passport is that it wants to be your login module but many times apps/sites want to enable account linking for data access aside from login (ex: login with Twitter and link your Facebook for integration) and passport isn't ideal for that use case.

**Comment by Stephn-R** [comment]
So are you looking at the case where a user would like to include several oauth login services like Twitter and/or Facebook? You mean Passport does not allow for this?

**Comment by arieljake** [comment]
Exactly. As I understand it, no it does not support it.

**Comment by Stephn-R** [comment]
Ok, we can investigate this further when including it. Perhaps we may need to include several plugins then unless there is another service that trumps Passport
