### ISSUE TITLE
NodeJS/Express middleware to include

### ISSUE THREAD

**Issue by Stephn-R** [gigster-eng/node-starter#14]
- [ ] [~~Morgan~~]()
- [x] [Winston](https://www.npmjs.com/package/winston)
- [x] [Compression](https://github.com/expressjs/compression)
- [x] [Body-Parser](https://github.com/expressjs/body-parser)
- [x] [Cookie-Parser](https://github.com/expressjs/cookie-parser)
- [x] [Error-Handler](https://github.com/expressjs/errorhandler)
- [ ] [~~Express-Session~~](https://github.com/expressjs/session)

**Comment by arieljake** [comment]
I find more plugins are available for Winston than Morgan

**Comment by Stephn-R** [comment]
Yep won me over on that. Winston has much more wide support

**Comment by arieljake** [comment]
Also maybe cookies and formidable

**Comment by Stephn-R** [comment]
I prefer cookie-parser instead. The parser adds the cookies as an object to the request object where as cookies requires us to instantiate the class by passing the request in. Etc etc.

**Comment by Stephn-R** [comment]
I also prefer body-parser since formidable was specifically designed for file uploads where as body-parser is a catch-all library

**Comment by Stephn-R** [comment]
We could include formidable for file uploads specifically if needed
