### ISSUE TITLE
Have we chosen gulp over grunt?

### ISSUE THREAD

**Issue by arieljake** [gigster-eng/node-starter#17]

**Comment by Stephn-R** [comment]
I personally prefer Gulp since it works with streams. But I am open for a debate.

**Comment by arieljake** [comment]
I just think grunt is more popular and has more plugins so it makes more sense.

**Comment by Stephn-R** [comment]
Yes but that should be the driving force. We should also consider the ability for it to interact with other existing services and the ease for any developer to pick up the system. 

I can equally debate that with gulp and easy starter templates ([ex](https://github.com/hparra/generator-gulp-plugin)) make it simple to write our own custom tools

**Comment by arieljake** [comment]
Right but gigster is pulling in devs from all over with different experience and we want to lower the ease of use on average with those devs

**Comment by Stephn-R** [comment]
Exactly, as such, we should pick one of these tools to help us better with project management rather than a folder full of bash/cmd scripts

**Comment by arieljake** [comment]
That's why I am pushing for grunt because it is more widely used in general and thus can be expected to be more widely used by future gigster devs

**Comment by Stephn-R** [comment]
Ok, lets just confirm on some of the other issues first. We may not need either if we will not have any front end code associated with this tool. Otherwise, Grunt/Gulp can be used easily for asset/project management
