### ISSUE TITLE
Examples for a basic DB setup

### ISSUE THREAD

**Issue by Stephn-R** [gigster-eng/node-starter#2]
What kind of options are there?

**Comment by arieljake** [comment]
I typically instantiate a db connection during configuration and save it to the express app locals for use in routes.

**Comment by Stephn-R** [comment]
Yes but how about DB type? Looking around, I see mongo is the option of choice but I am open to alternatives.

**Comment by Stephn-R** [comment]
**TIP** We could make this configurable when we setup yo to work with the template

**Comment by arieljake** [comment]
I think this needs to be customizable per client specs

**Comment by Stephn-R** [comment]
Alright so maybe we can offer several options within the app via folders:

    - Database
        - Mongo
        - Redis
        - EC2
        ...
        - config.js // specifies which folder to use for DB services

**Comment by arieljake** [comment]
Right. And we define a pattern that each database module must follow to integrate with config.js such as promise vs callback and what's returned.

**Comment by Stephn-R** [comment]
Great. I love the goal with it. So lets go ahead with that for the following DB systems:

- [ ] Redis
- [ ] Mongo
- [ ] EC2
- [ ] Firebase
- [ ] Postgresql
- [ ] Other?

**Comment by Stephn-R** [comment]
All have been built using a single engine >> `knex.js`
