### ISSUE TITLE
attach AngularJS as the base client side framework

### ISSUE THREAD

**Issue by Stephn-R** [gigster-eng/node-starter#6]

**Comment by arieljake** [comment]
Does it make sense to have the front end part of this project configurable? Or have a convention for other repos to follow to plugin in?

**Comment by Stephn-R** [comment]
I chimed the idea in another issue but perhaps when we setup Yo with the template, we can have an init setup that lets the user decide how their frontend will be constructed

I.E. > HTML, AngularJS, React, etc
